#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SENSORS_SSP_LIGHT_TMD3725)       += light_tmd3725.o
obj-$(CONFIG_SENSORS_SSP_LIGHT_TMD3700) += light_tmd3700.o
obj-$(CONFIG_SENSORS_SSP_LIGHT_TMG399X) += light_tmg399x.o