obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox_util.o abox_dbg.o abox_dump.o abox_log.o abox_gic.o abox.o abox_rdma.o abox_wdma.o abox_effect.o abox_vss.o abox_failsafe.o
obj-$(CONFIG_SEC_SND_SYNCHRONIZED_IPC) += abox_synchronized_ipc.o
obj-$(CONFIG_SEC_SND_ADAPTATION) += abox_adaptation.o