#
# Makefile for the Zinitix Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT532)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT541C)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX_TCLM)	+= zinitix_zt75xx_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX_WISDOM)	+= zinitix_zt75xx_ts.o

ccflags-$(CONFIG_SAMSUNG_TUI)	+= -Idrivers/misc/tui