# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos_ppmu.o exynos4_bus.o
obj-$(CONFIG_ARM_EXYNOS5_BUS_DEVFREQ)	+= exynos_ppmu.o exynos5_bus.o
obj-$(CONFIG_ARM_EXYNOS7885_BUS_DEVFREQ)+= exynos7885_bus_mif.o exynos7885_bus_int.o exynos7885_bus_disp.o exynos7885_bus_cam.o exynos7885_bus_aud.o exynos7885_bus_fsys.o
obj-$(CONFIG_ARM_EXYNOS7872_BUS_DEVFREQ)+= exynos7872_bus_mif.o exynos7872_bus_int.o exynos7872_bus_disp.o exynos7872_bus_cam.o
obj-$(CONFIG_EXYNOS_WD_DVFS)	+= exynos_ppmu.o
