#include "../pmucal_common.h"
#include "../pmucal_cpu.h"
#include "../pmucal_local.h"
#include "../pmucal_rae.h"
#include "../pmucal_system.h"

#include "pmucal_cpu_emulator8895.h"
#include "pmucal_local_emulator8895.h"
#include "pmucal_p2vmap_emulator8895.h"
#include "pmucal_system_emulator8895.h"

#include "cmucal-node.c"
#include "cmucal-qch.c"
#include "cmucal-sfr.c"
#include "cmucal-vclk.c"
#include "cmucal-vclklut.c"

#include "clkout_emulator8895.c"
#include "acpm_dvfs_emulator8895.h"
#include "asv_emulator8895.h"
