
obj-y	+= muic_usb.o muic-core.o muic_coagent.o muic_state.o muic_apis.o muic_sysfs.o muic_debug.o muic_dt.o muic_i2c.o muic_regmap.o muic_vps.o
obj-$(CONFIG_MUIC_SUPPORT_CCIC)	+= muic_ccic.o
obj-$(CONFIG_MUIC_UNIVERSAL_MAX77865)	+= muic_task_max77865.o muic_regmap_max77865.o
obj-$(CONFIG_MUIC_HV_MAX77865)		+= muic_hv_max77865.o

