obj-y					+= vpu-slab.o
obj-$(CONFIG_EXYNOS_VPU_LOOPBACK)	+= loopback/
obj-$(CONFIG_EXYNOS_VPU_HARDWARE)	+= hardware/
obj-y					+= translator/

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/vpu/include
