#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_ZH915)		+= zh915.o
obj-$(CONFIG_SEC_VIB)	+= sec_vib.o
obj-$(CONFIG_MOTOR_S2MU004)		+= s2mu004_haptic.o
obj-$(CONFIG_MOTOR_S2MU106)		+= s2mu106_haptic.o
obj-$(CONFIG_ISA1000)		+= isa1000.o

