obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o \
		fimc-is-interface-library.o \
		fimc-is-interface-vra.o \
		fimc-is-interface-ddk.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/vendor
