obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o
obj-$(CONFIG_OF)		+= sec_adc.o
obj-$(CONFIG_MULTI_CHARGING)	+= sec_multi_charger.o
obj-$(CONFIG_STEP_CHARGING)	+= sec_step_charging.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd.o
obj-$(CONFIG_UPDATE_BATTERY_DATA)	+= sec_battery_data.o
obj-$(CONFIG_BATTERY_NOTIFIER)	+= battery_notifier.o

obj-$(CONFIG_PM_S2MU106)  		+= s2mu106_pmeter.o
obj-$(CONFIG_FUELGAUGE_S2MU205)		+= s2mu205_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_S2MU106)		+= s2mu106_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_S2MU004)		+= s2mu004_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_S2MU005)		+= s2mu005_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX77865)	+= max77865_fuelgauge.o

obj-$(CONFIG_CHARGER_S2MU205)   += s2mu205_charger.o
obj-$(CONFIG_CHARGER_S2MU106)   += s2mu106_charger.o
obj-$(CONFIG_CHARGER_S2MU004)   += s2mu004_charger.o
obj-$(CONFIG_CHARGER_S2MU005)   += s2mu005_charger.o
obj-$(CONFIG_CHARGER_MAX77865)	+= max77865_charger.o
obj-$(CONFIG_CHARGER_BQ25898S)	+= bq25898s_charger.o
obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_ttf.o