obj-$(CONFIG_EXYNOS_VPU_ALC_DEFAULT)	+= vpu-hw-v2.1.o
obj-$(CONFIG_EXYNOS_VPU_ALC_DEFAULT)	+= vpu-hw-host-v2.1.o
obj-$(CONFIG_EXYNOS_VPU_ALC_DEFAULT)	+= vpu-hwmapper.o

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/vpu/include
