obj-$(CONFIG_EXYNOS_VPU_ALC_HWMAPPER)	+= vpul-hw-v2.1.o
obj-$(CONFIG_EXYNOS_VPU_ALC_HWMAPPER)	+= vpul-hw-host-v2.1.o
obj-$(CONFIG_EXYNOS_VPU_ALC_HWMAPPER)	+= vpul-latency-balancing.o
obj-$(CONFIG_EXYNOS_VPU_ALC_HWMAPPER)	+= vpul-hwmapper.o

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/vpu/include
