obj-$(CONFIG_CAMERA_IRIS_AK7372_OBJ) += fimc-is-iris-ak7372.o

ccflags-y := -Idrivers/media/platform/exynos/fimc-is2
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/include
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/vendor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/sensor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
