obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-legacy/sensor
