ccflags-y += -I$(srctree)/drivers/misc/tzdev/include

obj-$(CONFIG_TZDEV)		+= lib/

obj-$(CONFIG_TZDEV)		+= tzdev.o
obj-$(CONFIG_TZDEV)		+= sysdep.o
obj-$(CONFIG_TZDEV)		+= tz_cdev.o
obj-$(CONFIG_TZDEV)		+= tz_iwnotify.o
obj-$(CONFIG_TZDEV)		+= tz_kernel_api.o
obj-$(CONFIG_TZDEV)		+= tz_iwio.o
obj-$(CONFIG_TZDEV)		+= tz_platform.o
obj-$(CONFIG_TZDEV)		+= tz_mem.o
obj-$(CONFIG_TZDEV_CMA)		+= tz_cma.o
obj-$(CONFIG_ION_FD2PHYS)	+= ion_fd2phys.o
obj-$(CONFIG_TZIRS)		+= tzirs.o
obj-$(CONFIG_TZPROFILER)	+= tzprofiler.o
obj-$(CONFIG_TZTUI)		+= tztui_fts.o
obj-$(CONFIG_MSM_SCM)		+= tz_msm_platform.o
obj-$(CONFIG_TZ_TRANSPORT)	+= tz_transport.o
obj-$(CONFIG_TZ_TELEMETRY)	+= tz_telemetry.o
obj-$(CONFIG_TZLOG)		+= tz_iwlog.o
obj-$(CONFIG_TZLOG_POLLING)	+= tz_iwlog_polling.o
obj-$(CONFIG_TZDEV_HOTPLUG)	+= tz_hotplug.o
obj-$(CONFIG_TZDEV_BOOST)	+= tz_boost.o
obj-$(CONFIG_TZ_PANIC_DUMP)	+= tz_panic_dump.o
obj-$(CONFIG_TZ_BOOT_LOG)	+= tz_iw_boot_log.o
obj-$(CONFIG_TZ_SHMEM_VALIDATOR)	+= tz_shmem_validator.o
obj-$(CONFIG_TZ_WORMHOLE)	+= tz_wormhole.o

