#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_LSM6DSL)	+= gyro_lsm6dsl.o
obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_K6DS3TR)	+= gyro_k6ds3tr.o
obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_MPU6500)	+= gyro_mpu6500.o
obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_BMI168)	+= gyro_bmi168.o