#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SSP_PROXIMITY_AUTO_CAL_TMD3725) += prox_autocal_ams.o
obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMD3700) += prox_tmd3700.o
obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMD3725) += prox_tmd3725.o
obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMG399X) += prox_tmg399x.o