ifeq ($(CONFIG_SAMSUNG_PRODUCT_SHIP), y)
  obj-$(CONFIG_TOUCHSCREEN_SEC_INCELL_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o
else
  obj-$(CONFIG_TOUCHSCREEN_SEC_INCELL_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
endif

ccflags-$(CONFIG_SAMSUNG_TUI)	+= -Idrivers/misc/tui