#
# Makefile for the exynos video drivers.
#

obj-$(CONFIG_EXYNOS_LCD_S6E8AX0)	+= s6e8ax0.o
obj-$(CONFIG_EXYNOS_DECON_8890)	+= decon_8890/
obj-$(CONFIG_EXYNOS_DECON_8895)	+= dpu/
obj-$(CONFIG_EXYNOS_DECON_7872)	+= dpu_7872/
obj-$(CONFIG_EXYNOS_DECON_7885)	+= dpu_7885/
