#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS25H)	+= barometer_lps25h.o
obj-$(CONFIG_SENSORS_SSP_BAROMETER_BMP280)	+= barometer_bmp280.o
obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS22H)	+= barometer_lps22h.o