#
# Makefile for the Imagis touch driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_IST30XX) += ist30xxh.o ist30xxh_misc.o ist30xxh_sys.o ist30xxh_update.o ist30xxh_sec.o
obj-$(CONFIG_TOUCHSCREEN_IST3038H) += ist30xxh.o ist30xxh_misc.o ist30xxh_sys.o ist30xxh_update.o ist30xxh_sec.o ist30xxh_cmcs.o