#
# Makefile for usbpd devices
#

obj-$(CONFIG_CCIC_S2MU004)	+= s2mu004-usbpd.o
obj-$(CONFIG_CCIC_S2MU106)	+= s2mu106-usbpd.o
obj-$(CONFIG_CCIC_S2MU205)	+= s2mu205-usbpd.o
obj-$(CONFIG_USE_CCIC)		+= usbpd.o usbpd_cc.o
obj-$(CONFIG_USE_CCIC)		+= usbpd_policy.o usbpd_manager.o pdic_notifier.o ccic_misc.o
obj-$(CONFIG_CCIC_S2MM005)		+= s2mm005_fw.o s2mm005_cc.o s2mm005_pd.o s2mm005.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o 
obj-$(CONFIG_CCIC_ALTERNATE_MODE)	+= ccic_alternate.o ccic_misc.o
