#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#
#

MALI_CUSTOMER_RELEASE = 1
DEFINES +=-DMALI_SEC_PROBE_TEST=0

# MALI_SEC_SECURE_RENDERING
ifeq ($(CONFIG_MALI_EXYNOS_SECURE_RENDERING),y)
DEFINES +=-DMALI_SEC_SECURE_RENDERING=1
else
DEFINES +=-DMALI_SEC_SECURE_RENDERING=0
endif

# EXYNOS THERMAL
THERMAL_PATH = $(srctree)/drivers/thermal/samsung/

ccflags-y += $(DEFINES) -I$(THERMAL_PATH)
subdir-ccflags-y += $(DEFINES) -I$(THERMAL_PATH)

soc_name := $(shell echo $(CONFIG_EXYNOS_SOC_NAME))

obj-y += gpu_integration_callbacks.o
obj-y += mali_kbase_platform.o
obj-y += gpu_notifier.o
obj-y += gpu_exynos$(soc_name).o
obj-y += gpu_control.o
obj-y += gpu_pmqos.o
obj-y += gpu_utilization.o
obj-y += gpu_dvfs_handler.o
obj-y += gpu_dvfs_api.o
obj-y += gpu_dvfs_governor.o
obj-y += gpu_perf.o
obj-$(CONFIG_MALI_DEBUG_SYS) += gpu_custom_interface.o
obj-$(CONFIG_CPU_THERMAL_IPA) += gpu_ipa.o
