#
# Makefile for BTS.
#

obj-$(CONFIG_EXYNOS7885_BTS)    += cal_bts7885.o bts-exynos7885.o
obj-$(CONFIG_EXYNOS8890_BTS)    += cal_bts8890.o bts-exynos8890.o
obj-$(CONFIG_EXYNOS8895_BTS)    += cal_bts8895.o bts-exynos8895.o
obj-$(CONFIG_EXYNOS7872_BTS)    += cal_bts7872.o bts-exynos7872.o
